// These styles apply to every route in the application
import { NavBar } from '@/components/NavBar'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='m-0 w-full h-full'>
        <main className="flex flex-col p-12 h-screen w-screen">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  )
}
